### ISSUE TITLE
Generalization: "Russian (Ukraine) Translation"

### ISSUE THREAD

**Issue by NIRVANA101** [danieldanielecki/IT-ARMY-of-Ukraine-Resources-in-English#20]
I can automatically translate and manually review translations in multiple languages, including "**Russian (Ukraine)**"... though collaborator/write access may be required. It would be extremely beneficial to the project if the data could be shared with a larger number of people. After that, you might want to generalize the repository name...

_*This is only a suggestion._

**Comment by danieldanielecki** [comment]
@NIRVANA101, would you like to have collaborator access to what I understood?

**Comment by NIRVANA101** [comment]
To be straightforward, pretty much a yes... but kind of a requirement if you want the suggestion (generalization/translation) above. 
![image](https://user-images.githubusercontent.com/80667677/162555147-60255919-386a-4eaa-9219-9c27e72ad700.png)

**Comment by danieldanielecki** [comment]
@NIRVANA101 sure thing, collaborate granted; please confirm:)

**Comment by NIRVANA101** [comment]
Alrighty! Translations are on it's way!

**Comment by danieldanielecki** [comment]
@NIRVANA101, it looks good; much appreciated!:)

**Comment by NIRVANA101** [comment]
> @NIRVANA101, it looks good; much appreciated!:)

Alrighty! Planning to add other missing resources soon, so it'll be a complete page for Ukrainian readers.
