### ISSUE TITLE
ddosmonitor.herokuapp.com/ Seems down

### ISSUE THREAD

**Issue by MNF** [danieldanielecki/IT-ARMY-of-Ukraine-Resources-in-English#22]
https://ddosmonitor.herokuapp.com/ Seems down

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by NIRVANA101** [comment]
Not down, there's probably just some small error. Waiting for further instructions.

**Comment by danieldanielecki** [comment]
@NIRVANA101, the website is still down. I think @MNF is right.

**Comment by NIRVANA101** [comment]
> @NIRVANA101, the website is still down. I think @MNF is right.

I was waiting for your instructions, we should definitely just remove it.
