### ISSUE TITLE
Pro-Putin Telegram channels

### ISSUE THREAD

**Issue by MNF** [danieldanielecki/IT-ARMY-of-Ukraine-Resources-in-English#29]
I’ve created PR https://github.com/danieldanielecki/IT-ARMY-of-Ukraine-Resources-in-English/pull/28. 

Will you consider to host the Pro-Putin Telegram channels list in your repository? It will allow to maintain/ update it , add annotations such as number of subscribers.

**Comment by danieldanielecki** [comment]
Hey @MNF, I think it helps = whatever helps we can aceept, I feel :)

Merged!
